### ISSUE TITLE
Usage in flutter project

### ISSUE THREAD

**Issue by Darkoon** [mockturtl/dotenv#18]
Hi!

I'm trying to use dotenv package in simple Flutter project but can't get it work. 
Added `dotenv: ^1.0.0` in `pubspec.yaml` of the project, then imported it `import 'package:dotenv/dotenv.dart' as dotenv;` and used by calling `dotenv.load()` and `dotenv.env[myVar]`.

When debugging `load` method I found out that it cant find `.env` file in `_verify` so it's not adding any of my variables to env.

Are there any other steps I must do to make dotenv work with flutter? On which project structure level should I place my `.env` file (project root? lib? or maybe near dart file calling `load` ?).

**Comment by Idan-BM** [comment]
Same issue here...
Did you get it to work at the end?

**Comment by Darkoon** [comment]
@Idan-BM Aye, I used [flutter_dotenv](https://pub.dartlang.org/packages/flutter_dotenv) instead. If you want to check out how I used it visit my [flutter project repo ](https://github.com/Darkoon/Warehouse_mobile).

**Comment by golane-august** [comment]
Same for me. Any ideas for this lib?
