### ISSUE TITLE
annotate test-only methods

### ISSUE THREAD

**Issue by mockturtl** [mockturtl/dotenv#3]
Some methods are only public for testing, tagged `@Deprecated // FIXME`.  Revisit pending [interceptors/macros](https://github.com/sigmundch/DEP-member-interceptors/blob/master/proposal.md#example-2-debug-onlytest-only-features) proposal.

**Comment by mockturtl** [comment]
@sigmundch Has there been any movement on DEP-member-interceptors?  I think [dart-lang/dart_enhancement_proposals](https://github.com/dart-lang/dart_enhancement_proposals/issues) is the place to look for status updates, but I don't see it.

**Comment by sigmundch** [comment]
unfortunately no - there hasn't been much activity on it. It seems that I never filed an issue for it, so I just created it here: https://github.com/dart-lang/dart_enhancement_proposals/issues/44

**Comment by mockturtl** [comment]
Alternative: [`@visibleForTesting`](https://www.dartdocs.org/documentation/meta/1.0.4/meta/visibleForTesting-constant.html)
