### ISSUE TITLE
Allow parsing of the file without setting it in the env

### ISSUE THREAD

**Issue by smayas** [mockturtl/dotenv#30]
I have a use case where I need to parse the file and get all values as a Map without setting them in the env at the same time.
It would be nice if this is supported

**Comment by mockturtl** [comment]
I think this will be supported with #29.  Can you explain more about your use case?  Thanks!

**Comment by mockturtl** [comment]
@smayas I hope the new release addresses your use case.  You can load your file with a new `DotEnv` instance, and read its `map`.

You may need `//ignore: invalid_use_of_visible_for_testing_member` to silence a lint warning.

Feel free to reopen if this doesn't solve your problem.  Thanks!

**Comment by smayas** [comment]
Thanks for this. Will give it a try
